name: Debug Make Installation

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install basic build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential # Installs make and other essential tools

    - name: Verify make installation
      run: |
        make --version # Checks if make is installed

    - name: Verify CMake installation
      run: |
        cmake --version # Checks if CMake is installed
