name: Build and Package

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update and install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          mingw-w64 \
          cmake \
          build-essential # Install make and other build tools

    - name: Make build folder and CMake
      run: |
        mkdir -p _build_win32
        cd _build_win32
        cmake .. -G "Unix Makefiles" \
                 -DSERIOUS_PROTON_DIR=/ee-workspace/SeriousProton \
                 -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw.toolchain \
                 -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build . --target package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: EE Builder
        path: _build_win32/EmptyEpsilon.zip
